#!/bin/bash
# Mounts your Kindle, opens ann2html and unmounts the Kindle when it closes.
# Plug in your Kindle, then run this script.
kindle_UUID=

set -e
already_mounted=false
if df | grep -q "$(blkid -U "$kindle_UUID")"; then
	already_mounted=true
	echo "Device already mounted, will keep it mounted"
else
	udisksctl mount -b "/dev/disk/by-uuid/$kindle_UUID"
	echo "Device found and mounted!"
fi

"$(dirname "$(readlink -f "$0")")/ann2html" || ann2html

if [ "$already_mounted" = false ]; then
	udisksctl unmount -b "/dev/disk/by-uuid/$kindle_UUID"
fi
